#!/usr/bin/env bash
# One-click deployment for Prodigee Audio PD Evaluation System.
#
# Prerequisites:
#   - AWS CLI configured (aws configure or AWS_PROFILE set)
#   - Terraform >= 1.0 on PATH
#   - Python 3.x on PATH
#   - Node.js >= 18 on PATH
#
# Usage:
#   ./deploy.sh                          # deploy dev to ap-south-1
#   ./deploy.sh prod us-east-1           # deploy prod to us-east-1

set -euo pipefail

ENVIRONMENT="${1:-dev}"
REGION="${2:-ap-south-1}"

echo ""
echo "========================================"
echo " Prodigee Audio PD — Deployment Script"
echo " Environment : $ENVIRONMENT"
echo " Region      : $REGION"
echo "========================================"
echo ""

# ── Step 1: Verify AWS credentials ────────────────────────────────────────
echo "[1/5] Checking AWS credentials..."
ACCOUNT=$(aws sts get-caller-identity --query Account --output text 2>&1) || {
    echo "ERROR: AWS credentials not configured. Run 'aws configure' first."
    exit 1
}
echo "      Account: $ACCOUNT"
echo ""

# ── Step 2: Build Lambda packages ─────────────────────────────────────────
echo "[2/5] Building Lambda packages..."
python create_excel_package.py
echo "      excel-generator package built"
echo "      Other lambda packages will be zipped by Terraform"
echo ""

# ── Step 3: Terraform init + apply ────────────────────────────────────────
echo "[3/5] Running Terraform..."
pushd terraform > /dev/null

terraform init -upgrade
terraform apply -auto-approve \
    -var="environment=$ENVIRONMENT" \
    -var="aws_region=$REGION"

API_ENDPOINT=$(terraform output -raw api_endpoint)
popd > /dev/null

echo "      Infrastructure deployed"
echo "      API endpoint: $API_ENDPOINT"
echo ""

# ── Step 4: Write frontend .env ────────────────────────────────────────────
echo "[4/5] Updating frontend/.env..."
cat > frontend/.env <<EOF
# Auto-generated by deploy.sh — do not edit manually
VITE_AWS_REGION=$REGION
VITE_API_ENDPOINT=$API_ENDPOINT
VITE_DEBUG=false
EOF
echo "      frontend/.env updated"
echo ""

# ── Step 5: Build frontend ─────────────────────────────────────────────────
echo "[5/5] Building frontend..."
pushd frontend > /dev/null
npm install --silent
npm run build
popd > /dev/null
echo "      Frontend built → frontend/dist/"
echo ""

# ── Done ───────────────────────────────────────────────────────────────────
echo "========================================"
echo " Deployment Complete!"
echo "========================================"
echo ""
echo " API Endpoint : $API_ENDPOINT"
echo " Frontend     : frontend/dist/ (serve or upload to S3/CloudFront)"
echo ""
echo " IMPORTANT: Enable Bedrock model access manually if first deploy:"
echo "   AWS Console → Bedrock → Model access → Enable Claude 3.5 Sonnet (cross-region inference)"
echo ""
