#!/usr/bin/env pwsh
<#
.SYNOPSIS
    One-click deployment for Prodigee Audio PD Evaluation System.

.DESCRIPTION
    1. Builds the Excel Generator Lambda package (needs openpyxl)
    2. Runs terraform init + apply to provision all AWS infrastructure
    3. Writes the API endpoint into frontend/.env
    4. Builds the frontend

.PREREQUISITES
    - AWS CLI configured: aws configure (or set AWS_PROFILE env var)
    - Terraform >= 1.0 installed and on PATH
    - Python 3.x installed
    - Node.js >= 18 installed

.PARAMETER Environment
    Target environment: dev (default), uat, prod

.PARAMETER Region
    AWS region (default: ap-south-1)

.EXAMPLE
    .\deploy.ps1
    .\deploy.ps1 -Environment prod -Region us-east-1
#>

param(
    [string]$Environment = "dev",
    [string]$Region = "ap-south-1"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Prodigee Audio PD — Deployment Script" -ForegroundColor Cyan
Write-Host " Environment : $Environment" -ForegroundColor Cyan
Write-Host " Region      : $Region" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Verify AWS credentials ────────────────────────────────────────
Write-Host "[1/5] Checking AWS credentials..." -ForegroundColor Yellow
$identity = aws sts get-caller-identity --output json 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: AWS credentials not configured. Run 'aws configure' first." -ForegroundColor Red
    exit 1
}
$identity = $identity | ConvertFrom-Json
Write-Host "      Account : $($identity.Account)" -ForegroundColor Green
Write-Host "      User ARN : $($identity.Arn)" -ForegroundColor Green
Write-Host ""

# ── Step 2: Build Excel Generator Lambda package ──────────────────────────
Write-Host "[2/5] Building Lambda packages..." -ForegroundColor Yellow

# Build excel-generator package (requires openpyxl in package/ dir)
python create_excel_package.py
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Failed to build excel-generator package." -ForegroundColor Red
    exit 1
}
Write-Host "      excel-generator package built" -ForegroundColor Green

# Evaluation lambda is pure Python stdlib + boto3 (Lambda runtime provides boto3)
# Terraform archive_file will zip lambda/ dirs directly — no pre-build needed
Write-Host "      Other lambda packages will be zipped by Terraform" -ForegroundColor Green
Write-Host ""

# ── Step 3: Terraform init + apply ────────────────────────────────────────
Write-Host "[3/5] Running Terraform..." -ForegroundColor Yellow

Push-Location terraform

Write-Host "      terraform init..." -ForegroundColor Gray
terraform init -upgrade
if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Host "ERROR: terraform init failed." -ForegroundColor Red; exit 1 }

Write-Host "      terraform apply..." -ForegroundColor Gray
terraform apply -auto-approve `
    -var="environment=$Environment" `
    -var="aws_region=$Region"
if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Host "ERROR: terraform apply failed." -ForegroundColor Red; exit 1 }

# Capture outputs
$API_ENDPOINT = terraform output -raw api_endpoint
Pop-Location

Write-Host "      Infrastructure deployed" -ForegroundColor Green
Write-Host "      API endpoint: $API_ENDPOINT" -ForegroundColor Green
Write-Host ""

# ── Step 4: Write frontend .env ────────────────────────────────────────────
Write-Host "[4/5] Updating frontend/.env..." -ForegroundColor Yellow

$envContent = @"
# Auto-generated by deploy.ps1 — do not edit manually
VITE_AWS_REGION=$Region
VITE_API_ENDPOINT=$API_ENDPOINT
VITE_DEBUG=false
"@

Set-Content -Path "frontend\.env" -Value $envContent
Write-Host "      frontend/.env updated with API endpoint" -ForegroundColor Green
Write-Host ""

# ── Step 5: Build frontend ─────────────────────────────────────────────────
Write-Host "[5/5] Building frontend..." -ForegroundColor Yellow

Push-Location frontend
npm install --silent
if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Host "ERROR: npm install failed." -ForegroundColor Red; exit 1 }

npm run build
if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Host "ERROR: npm run build failed." -ForegroundColor Red; exit 1 }

Pop-Location
Write-Host "      Frontend built → frontend/dist/" -ForegroundColor Green
Write-Host ""

# ── Done ───────────────────────────────────────────────────────────────────
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Deployment Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host " API Endpoint : $API_ENDPOINT" -ForegroundColor White
Write-Host " Frontend     : frontend/dist/ (serve or upload to S3/CloudFront)" -ForegroundColor White
Write-Host ""
Write-Host " IMPORTANT: Enable Bedrock model access manually if first deploy:" -ForegroundColor Yellow
Write-Host "   AWS Console → Bedrock → Model access → Enable Claude 3.5 Sonnet" -ForegroundColor Yellow
Write-Host ""
